---
title: "DayOne preprocess for mysterybox"
author: "Ian Lo"
date: "10/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
# Load the package required to read JSON files.
library(jsonlite)
filename = "./Journal_ZB_290420.json"


# Give the input file name to the function.
json.dayone <- fromJSON(filename)
```
```{r}
#look at the first element of json.dayone$entries 
json.dayone$entries[1,] #this is the Day One data for a single entry
```

```{r}
#work with one entry 
single.entry <- json.dayone$entries[1,]

#flatten to make it easier to read
flat.single.entry <- flatten(single.entry)
```

```{r}
# unflatten(flat.single.entry)
```

```{r}
#only display fields I want
flat.single.entry[,c("creationDate",  
                     "location.localityName", 
                     "location.administrativeArea", 
                     "location.country",
                     "text",
                     "timeZone",
                     "uuid",
                     "weather.conditionsDescription",
                     "weather.pressureMB",
                     "weather.relativeHumidity",
                     "weather.temperatureCelsius",
                     "weather.visibilityKM",
                     "weather.weatherCode",
                     "weather.weatherServiceName",
                     "weather.windBearing",
                     "weather.windChillCelsius",
                     "weather.windSpeedKPH"
                     )]
```

```{r}
out<- c()
for (x in 1:nrow(json.dayone[["entries"]])){
  single.entry <- flatten(json.dayone[["entries"]][x,])
  
  #specify fields to export for analysis
  exp_entry <- (single.entry[,c("text",
                                "creationDate",  
                                "location.localityName", 
                                "location.administrativeArea", 
                                "location.country",
                                "timeZone",
                                "uuid",
                                "weather.conditionsDescription",
                                "weather.pressureMB",
                                "weather.relativeHumidity",
                                "weather.temperatureCelsius",
                                "weather.visibilityKM",
                                "weather.weatherCode",
                                "weather.weatherServiceName",
                                "weather.windBearing",
                                "weather.windChillCelsius",
                                "weather.windSpeedKPH"
                                )
                             ]
                )
  
    num_words <- sapply(strsplit(exp_entry$text, " "), length)
    # print(((num_words)))
    
    if (num_words < 4) {
      out$emoji <- rbind(out$emoji, exp_entry)
    }else{
      out$text <- rbind(out$text, exp_entry)
    }
    # print(exp_entry)
}
  

```

```{r}
out$emoji$mood <- c(rep("add your mood data as a number here", nrow(out$emoji)))
```


```{r}
out$emoji <- cbind(text = out$emoji[,1], mood = out$emoji[,18], out$emoji[,2:17])
```


```{r}
```

```{r}
file.noext <- tools::file_path_sans_ext(filename)
write.csv(out$emoji, file = paste((file.noext), "_emoji_output.csv", sep = ""))
print(paste((file.noext), "_emoji_output.csv", sep = ""))
write.csv(out$text, file = paste((file.noext), "_text_output.csv", sep = ""))
print(paste((file.noext), "_text_output.csv", sep = ""))
```


```{r}
```

